<a href="https://colab.research.google.com/github/maurimendiluce/Clases-Mate2/blob/main/Matrices_Jacobi_Gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Métodos de Jacobi y Gauss-Siedel

###Matrices: 
 
 Para trabajar con matrices usamos `np.array()`. 

##Veamos algunos ejemplos para selelcionar coordenadas, filas o columnas.

In [ ]:
import numpy as np
A = np.array([[1,7], [3,9]])
print(A)

[[1 7]
 [3 9]]


In [ ]:
print(A[0,1])   # Fila 0, columna 1

7


In [ ]:
print(A[0,0])   # Fila 0, columna 0

1


In [ ]:
print(A[0][1])   # Fila 0, columna 1.    Otra Forma de hacer lo mismo 

7


In [ ]:
print(A[1,:])   # Seleccionar la Fila 1. Lo devuelve como un array 1-dimesional.
#print(A[1])     # Otra forma de seleccionar Fila 1

[3 9]


In [ ]:
print(A[:, 0])   # Seleccionar Columna 0. Lo devuelve como un array 1-dimesional.

[1 3]


##Productos de Matrices

In [ ]:
B = np.array([[2,0],[0,1]])
print(B)

[[2 0]
 [0 1]]


In [ ]:
# OJO, no es el prod matricial usual! El producto es punto a punto, igual que el producto de array 1-dimensionales.
A*B

array([[2, 0],
       [0, 9]])

In [ ]:
# Para hacer el producto de matrices se usa el comando np.dot
np.dot(B, A)

array([[ 2, 14],
       [ 3,  9]])

## Más comandos

In [ ]:
At = np.transpose(A) # Traspone la matriz
print(A)
print(At)

[[1 7]
 [3 9]]
[[1 3]
 [7 9]]


In [ ]:
D = np.diag(A)
print(D)  # Devuelve la diagonal como un array 1-dimensional

[1 9]


In [ ]:
np.diag(np.diag(A))  # Convierte un array 1-dimesional a matriz diagonal

array([[1, 0],
       [0, 9]])

In [ ]:
np.diag([1,9]) #Lo mismo que antes

array([[1, 0],
       [0, 9]])

In [ ]:
M = np.random.rand(4,4)   # Matriz de números aleatorios entre 0 y 1
print(M)
print(np.zeros((4,4)))    # Matriz de ceros

In [ ]:
print("L = \n", np.tril(M, -1))   # Parte abajo de la diagonal. Agregamos la opción -1 para que no incluya a la diagonal
print("U = \n", np.triu(M, +1))   # Parte arriba de la diagonal. Agregamos la opción +1 para que no incluya a la diagonal


## El paquete `numpy.linalg`


In [ ]:
# Autovalores
print(B)
e = np.linalg.eig(B)
print(e)


In [ ]:
print(e[0])   # Autovalores

[2. 1.]


In [ ]:
print(e[1])   # Autovectores asociados a cada autovalor

In [ ]:
# Determinantes
print(A)
print(np.linalg.det(A))
print(np.linalg.det(B))

In [ ]:
# Inversas 
print(np.linalg.inv(A))
print(np.linalg.inv(B))

### Jacobi y Gauss Siedel
- Recomendación: mirar wikipedia 


#### Jacobi

Para resolver el sistema
$$
A{x} ={b} 
$$
utilizamos la iteración
$$
x^{(k+1)}=D^{-1}(-(L+U)) {x} ^{(k)} + D^{-1}b = D^{-1}((-(L+U) {x} ^{(k)} + b)
$$

**Ejemplo:** Implementar el método de Jacobi (en forma matricial) y utilizarlo para resolver el sistema $Ax = b$ con
$$
A = 
\begin{pmatrix}
5 & 2 & 1 & 1 \\
2 & 6 & 2 & 1 \\
1 & 2 & 7 & 1 \\
1 & 1 & 2 & 8
\end{pmatrix}
$$
y
$$
b = (29, 31, 26, 19)^t
$$


In [ ]:
def jacobi(A, b, x0, eps=1e-10, n=500):   # los parámetros eps y n se los pasamos por defectopor defecto
    D = np.diag(np.diag(A))
    LU = A - D
    x = x0
    D_inv = np.linalg.inv(D)
    for i in range(n):
        xTemp = x
        x = np.dot(D_inv, np.dot(-(LU), x) + b)   
        print('paso:', i, '- x:', x)
        if np.linalg.norm(x - xTemp) < eps:    # norm nos la norma de un vector
            return x
    return x


In [ ]:
A = np.array([
    [5, 2, 1, 1],
    [2, 6, 2, 1],
    [1, 2, 7, 1],
    [1, 1, 2, 8]
])
b = np.array([29, 31, 26, 19])

x0 = np.random.rand(4)
x = jacobi(A, b, x0, 10**(-14), 500)    # Si no ingresamos los ultimos valores, usa los valores por defecto

print('x:', x)
print('b calculado:', np.dot(A, x))
print('b verdadero:', b)
print('solución de numpy:', np.linalg.solve(A,b))

#Ejercicio:
 
Modificar el programa anterior para que aplique el método de Gauss-Siedel, dado por la iteración
$$
{x} ^{(k+1)}=(L+D)^{-1}({b} -U {x} ^{(k)}).
$$

Resolver el sistema anterior utilizando Gauss-Siedel y comparar la cantida de pasos.

#Convergencia del método de Jacobi usando comandos de `numpy`


**Ejemplo:** 

- Para 
$$
A={\begin{pmatrix}29&2&1\\2&6&1\\1&1&{\frac {1}{5}}\end{pmatrix}}
$$

y 

$$
b = [1, 2, 3]^t
$$

determinar si el sistema $Ax = b$ es convergente para cualquier vector inicial $x_0$.

- Verificar la respuesta tomando distintos vectores iniciales.

In [ ]:
A = np.array([[29, 2, 1], [2, 6, 1], [1, 1, 1/5]])
D = np.diag(np.diag(A))
LU = A - D
BJ = np.dot(np.linalg.inv(D), -LU)
print(BJ)

In [ ]:
np.linalg.eig(BJ)

In [ ]:
b = np.array([1,2,3])
#x0 = np.random.rand(3)
x0 = np.zeros(3)
x = jacobi(A, b, x0)    # Si no ingresamos los ultimos valores, usa los valores por defecto

print('x:', x)
print('b calculado:', np.dot(A, x))
print('b verdadero:', b)
print('solución de numpy:', np.linalg.solve(A,b))